name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  BuildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone tree
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            libboost-all-dev \
            llvm
      - name: Compile
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j$(grep -c processor /proc/cpuinfo)
      - name: Test
        run: |
          ctest --test-dir build --output-on-failure
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox_bios_tool_linux
          path: build/xbox_bios_tool

  BuildMacOS:
    name: Build macOS
    runs-on: macOS-latest
    steps:
      - name: Clone tree
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install \
            cmake \
            coreutils \
            boost \
            llvm
      - name: Compile
        run: |
          export PATH="$(brew --prefix llvm@18)/bin:$PATH"
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j
      - name: Test
        run: |
          ctest --test-dir build --output-on-failure
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox_bios_tool_macos
          path: build/xbox_bios_tool

  BuildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2.0.0
      - name: Build solution
        run: msbuild vc/XboxBiosTools.sln /p:Configuration=Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xbox_bios_tool_win64
          path: |
            bin
